trigger:
- main

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Build FirstJob
    - script: echo $(Build.BuildNumber)
    - script: echo $(Build.BuildId)
    - script: echo $(Build.BuildNumber)
    - script: echo $(Build.SourceBranchName)
    - script: echo $(Build.SourcesDirectory)
    #- script: ls -R $(System.DefaultWorkingDirectory)
    - script: dir /s "$(System.DefaultWorkingDirectory)"
    - script: echo $(Build.ArtifactStagingDirectory)
    - script: java -version
    - script: node --version
    - script: python --version 
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - script: dir /s "$(System.DefaultWorkingDirectory)"
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'




#   - job: SecondJob
#     steps:
#     - script: echo Build SecondJob

# - stage: DevDeploy
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - script: echo DevDeployJob

# - stage: QADeploy
#   dependsOn: DevDeploy
#   jobs:
#   - job: QADeployJob
#     steps:
#     - script: echo QADeployJob

# - stage: ProdDeploy
#   dependsOn: 
#    - Build
#    - DevDeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - script: echo ProdDeployJob
