trigger:
- main

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Build FirstJob

  - job: SecondJob
    steps:
    - script: echo Build SecondJob

- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - script: echo DevDeployJob

- stage: QADeploy
  dependsOn: DevDeploy
  jobs:
  - job: QADeployJob
    steps:
    - script: echo QADeployJob

- stage: ProdDeploy
  dependsOn: 
   - Build
   - DevDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - script: echo ProdDeployJob
